# 基础配置文件
nft:
  turbo: # TODO：这个后期修改一下前缀
    nacos:
      server:
        url: 114.132.166.26:8848 # nft.turbo.nacos.server.url
    mysql:
      url: jdbc:mysql://114.132.166.26:3306/nfturbo # nft.turbo.mysql.url
      username: nfturbo # nft.turbo.mysql.username
      password: 'NFTurbo666' # nft.turbo.mysql.password
    redis:
      url: 114.132.166.26  # nft.turbo.redis.url
      port: 6379 # nft.turbo.redis.port
      password: 'NFTurbo666' # nft.turbo.redis.password
    elasticsearch:
      enable: false # nft.turbo.elasticsearch.enable
      url: 114.132.166.26:9200 # nft.turbo.elasticsearch.url
      username: elastic # nft.turbo.elasticsearch.username
      password: 123456  # nft.turbo.elasticsearch.password
    xxl-job:
      url: 114.132.166.26:23333  # nft.turbo.xxl-job.url
      appName: xxl-job-executor  # nft.turbo.xxl-job.appName
      accessToken: default_token # nft.turbo.xxl-job.accessToken
    sentinel:
      url: 114.132.166.26:8099 # nft.turbo.sentinel.url
      port: 8098 # nft.turbo.sentinel.port
      nacos:
        data-id: nfturbo-gateway-sentinel # nft.turbo.sentinel.nacos.data-id
    rocketmq:
      url: 114.132.166.26:9876 # nft.turbo.rocketmq.url - RocketMQ 的地址+端口号 # 如果你要用RocketMQ，这里需要改成你自己的
    dubbo:
      nacos:
        namespace: dubbo_server  # nft.turbo.dubbo.nacos.namespace
        group: dubbo1  # nft.turbo.dubbo.nacos.group
    seata:
      nacos:
        data-id: seataServer.properties # nft.turbo.seata.nacos.data-id
        group: seata # nft.turbo.seata.nacos.group
        namespace: seata_server # nft.turbo.seata.nacos.namespace
